### ISSUE TITLE
Unable to use GUI

### ISSUE THREAD

**Issue by cadeichsel** [wildrootlab/SHARCQ#4]
Hello,

I am very new to MATLAB, but I wanted to try out the GUI with the example images provided in the wiki, but immediately  I run into a problem in the first  step where it does not recognize the Process_Histology  function as a function. Could you please let me  know what I am doing wrong?  I am using R2022a. 

<img width="1351" alt="Screen Shot 2022-05-10 at 14 19 03" src="https://user-images.githubusercontent.com/71463456/167626749-8ba0e43a-f49a-4a8a-8b03-466f528f380b.png">

**Comment by dhino2000** [comment]
Did you run SHARCQ from command window?
I double-clicked "SHARCQ.mlapp".

**Comment by cadeichsel** [comment]
Yes I ran it from the command window, and can open it fine. The GUI starts. When I try to use it- pre-process images, then it does not work and I get the error shown above.

**Comment by dhino2000** [comment]
Please see the trouble shooting.
(https://github.com/wildrootlab/SHARCQ/wiki/9.-Troubleshooting)
By adding SHARCQ-master to Matlab path, it may work for now.

**Comment by cadeichsel** [comment]
Thank you! I thought I had already put it into the correct path. But I guess not. Thanks for your help!
